# Run configurations: Choose from 'vqe', 'redundant', and 'zne'.
run: "vqe-bigT-simulation"
bigT: [15, 20.0, 30.0, 40, 45]

# System configuration
nqubits: 3
# State options: 'dmatrix' and 'statevector'
state: "dmatrix"

# Output configuration
output:
  file_name_prefix: "vqe-time-rel-noise-experement" #heisenberg_ansatz_ric3_sample#1 
  draw:
    status: True
    fig_dpi: 100
    type: "png"

# Target Hamiltonian configuration
observable:
  # Definition options: 'custom', 'ising', or 'heisenberg'.
  # 'custom' and 'ising' are created using a Hamiltonian with terms XZ-Z (this is NOT any standard familier XY model, we call it 'Fancy XY-model Hamiltonian').
  def: "ising"

  # WARNING: Coefficients can be overwritten:
  # 'custom': Not overwritten.
  # 'ising': cn, bn, r are overwritten to [0.5], [1], 1.
  # 'heisenberg': Only cn is used (will NOT be overwritten); bn and r are not used.
  coefficients:
    cn: [0.5, 0.5]
    bn: [1.0, 1.0, 1.0]
    r: 1

# Circuit configuration
ansatz:
  layer: 30
  # Not tested. Keep gateset=1, there could be bugs.
  gateset: 1
  ugate:
    # Type options: 'custom', 'xy-iss', 'ising', and 'heisenberg'.
    # 'custom' and 'ising' are created using a Hamiltonian with terms XZ-Z (this is NOT any standard familier XY model, we call it 'Fancy XY-model Hamiltonian').
    type: "xy-iss"
    # WARNING: For ZNE redundant circuit, the ansatz type must be 'xy-iss' (stands for XY identity-scaling-supported).
    
    coefficients:
    # WARNING: Coefficients can be overwritten:
    # 'custom': Not overwritten.
    # 'xy-iss': cn, bn, r are overwritten to [0.5], [0], 0.
    # 'ising': cn, bn, r are overwritten to [0.5], [1], 1.
    # 'heisenberg': Only cn is used (will NOT be overwritten); bn and r are not used.
      cn: [0.5, 0.5]
      bn: [0, 0, 0]
      r: 0
    time:
      min: 0.0
      max: 100.0

# Variational Quantum Eigensolver (VQE) configuration
vqe:
  iteration: 1
  # Optimization configuration
  optimization:
    status: True
    algorithm: "SLSQP"
    constraint: True

# Initial parameters for the ansatz.
init_param:
  # Parameter value: "random" or "List[floats]".
  value: "random"

# Noise configuration
noise_profile:
  status: False
  type: "dephasing" # Choose from 'depolarizing', 'bitflip', 'dephasing', or 'xznoise'.
  noise_prob: [0.001, 0.001, 0.0, 0.0] # Noise probabilities for [R, CZ, U, Y] gates.
  noise_on_init_param:
    # NOT IMPLEMENTED! Adds noise to the initial parameters.
    status: False
    value: 0

# Redundant circuit configuration
redundant:
  # Identity factors for [R, CZ, U, Y] gates.
  # WARNING: Identity scaling for the U gate is only possible if vqe.ansatz.type is 'xy-iss'. For other types, the identity factor for the U gate must be set to 0.
  identity_factors: [[0, 0, 0, 0], [1, 1, 1, 1]]

# Zero noise extrapolation (ZNE) configuration
zne:
  # Method options: 'linear', 'polynomial', 'richardson', or 'richardson-mul'.
  # 'linear' and 'polynomial' use scikit-learn for regression.
  method: "richardson"

  # Degree is only applicable for 'polynomial' and 'richardson-mul'. The 'richardson' method does not accept degree as a parameter.
  degree: 1

  # Sampling method options: 'default', 'default-N', or 'random-N', where N is an integer.
  # 'default' - samples all points.
  # 'default-N' - samples the first N points.
  # 'random-N' - samples N points randomly.
  sampling: "default"

  # Data points for extrapolation
  data_points:  